// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXpLQIkuGb0dFLp9fw1nHq_OCR9Kq-s0',
    appId: '1:105595501715:web:35ce9de6d69f6d2fc16166',
    messagingSenderId: '105595501715',
    projectId: 'dinariv0',
    authDomain: 'dinariv0.firebaseapp.com',
    storageBucket: 'dinariv0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzXpLQIkuGb0dFLp9fw1nHq_OCR9Kq-s0',
    appId: '1:105595501715:android:35ce9de6d69f6d2fc16166',
    messagingSenderId: '105595501715',
    projectId: 'dinariv0',
    storageBucket: 'dinariv0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXpLQIkuGb0dFLp9fw1nHq_OCR9Kq-s0',
    appId: '1:105595501715:ios:35ce9de6d69f6d2fc16166',
    messagingSenderId: '105595501715',
    projectId: 'dinariv0',
    storageBucket: 'dinariv0.firebasestorage.app',
    iosBundleId: 'com.example.dinari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXpLQIkuGb0dFLp9fw1nHq_OCR9Kq-s0',
    appId: '1:105595501715:ios:35ce9de6d69f6d2fc16166',
    messagingSenderId: '105595501715',
    projectId: 'dinariv0',
    storageBucket: 'dinariv0.firebasestorage.app',
    iosBundleId: 'com.example.dinari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXpLQIkuGb0dFLp9fw1nHq_OCR9Kq-s0',
    appId: '1:105595501715:web:35ce9de6d69f6d2fc16166',
    messagingSenderId: '105595501715',
    projectId: 'dinariv0',
    authDomain: 'dinariv0.firebaseapp.com',
    storageBucket: 'dinariv0.firebasestorage.app',
  );

}
